wip initial stack

diff --git a/.github/workflows/publish-infra.yml b/.github/workflows/publish-infra.yml
--- a/.github/workflows/publish-infra.yml
+++ b/.github/workflows/publish-infra.yml
@@ -107,101 +107,101 @@ jobs:
           terraform apply -target=module.initial --auto-approve -input=false -var-file=${{ env.environment }}.tfvars
         working-directory: ${{ env.WORKING_DIRECTORY }}       
         
-      - name: Log in to the GHCR
-        uses: docker/login-action@v3
-        with:
-          registry: ghcr.io
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
+      # - name: Log in to the GHCR
+      #   uses: docker/login-action@v3
+      #   with:
+      #     registry: ghcr.io
+      #     username: ${{ github.actor }}
+      #     password: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Setup Image Metadata
-        id: meta
-        uses: docker/metadata-action@v5
-        with:
-          images: |
-            ${{ env.GITHUB_IMAGE_REPO }}/${{ env.DUMMY_IMAGE_NAME }}
-          tags: |
-            type=raw,value=latest
+      # - name: Setup Image Metadata
+      #   id: meta
+      #   uses: docker/metadata-action@v5
+      #   with:
+      #     images: |
+      #       ${{ env.GITHUB_IMAGE_REPO }}/${{ env.DUMMY_IMAGE_NAME }}
+      #     tags: |
+      #       type=raw,value=latest
 
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
-        with:
-          driver: docker
+      # - name: Set up Docker Buildx
+      #   uses: docker/setup-buildx-action@v3
+      #   with:
+      #     driver: docker
 
-      - name: Build ${{ env.DUMMY_IMAGE_NAME }} image
-        uses: docker/build-push-action@v6
-        with:
-          push: true
-          file: ./docker/dummy-image/Dockerfile.release
-          context: .
-          tags: ${{ steps.meta.outputs.tags }}
-          labels: ${{ steps.meta.outputs.labels }}
+      # - name: Build ${{ env.DUMMY_IMAGE_NAME }} image
+      #   uses: docker/build-push-action@v6
+      #   with:
+      #     push: true
+      #     file: ./docker/dummy-image/Dockerfile.release
+      #     context: .
+      #     tags: ${{ steps.meta.outputs.tags }}
+      #     labels: ${{ steps.meta.outputs.labels }}
 
-      - name: Login to Amazon ECR
-        uses: aws-actions/amazon-ecr-login@v2
+      # - name: Login to Amazon ECR
+      #   uses: aws-actions/amazon-ecr-login@v2
 
-      - name: Check dummy-image in App ECR exists
-        id: app-ecr-check
-        shell: bash
-        run: |
-          IMAGE_TAG=${{ env.DUMMY_IMAGE_NAME }}
-          REPOSITORY_NAME=${{ vars.APP_NAME }}-app-repo-${{ env.environment }}
+      # - name: Check dummy-image in App ECR exists
+      #   id: app-ecr-check
+      #   shell: bash
+      #   run: |
+      #     IMAGE_TAG=${{ env.DUMMY_IMAGE_NAME }}
+      #     REPOSITORY_NAME=${{ vars.APP_NAME }}-app-repo-${{ env.environment }}
           
-          IMAGE_EXISTS=$(aws ecr describe-images --repository-name $REPOSITORY_NAME --query "imageDetails[?contains(imageTags, '$IMAGE_TAG')]" --output text)
+      #     IMAGE_EXISTS=$(aws ecr describe-images --repository-name $REPOSITORY_NAME --query "imageDetails[?contains(imageTags, '$IMAGE_TAG')]" --output text)
 
-          if [ -z "$IMAGE_EXISTS" ]; then
-            echo "Image with tag $IMAGE_TAG does not exist."
-            echo "exists=false" >> $GITHUB_OUTPUT
-          else
-            echo "Image with tag $IMAGE_TAG already exists."
-            echo "exists=true" >> $GITHUB_OUTPUT
-          fi
+      #     if [ -z "$IMAGE_EXISTS" ]; then
+      #       echo "Image with tag $IMAGE_TAG does not exist."
+      #       echo "exists=false" >> $GITHUB_OUTPUT
+      #     else
+      #       echo "Image with tag $IMAGE_TAG already exists."
+      #       echo "exists=true" >> $GITHUB_OUTPUT
+      #     fi
           
-      - name: Push dummy image to App ECR
-        if: steps.app-ecr-check.outputs.exists == 'false'
-        shell: bash
-        run: |
-          echo 'Deploying ${{ env.DUMMY_IMAGE_NAME }} to App ECR'
-          docker tag  ${{ env.GITHUB_IMAGE_REPO }}/${{ env.DUMMY_IMAGE_NAME }}:latest ${{ env.APP_ECR_REPO_URL }}:${{ env.DUMMY_IMAGE_NAME }}
-          docker push ${{ env.APP_ECR_REPO_URL }}:${{ env.DUMMY_IMAGE_NAME }}
+      # - name: Push dummy image to App ECR
+      #   if: steps.app-ecr-check.outputs.exists == 'false'
+      #   shell: bash
+      #   run: |
+      #     echo 'Deploying ${{ env.DUMMY_IMAGE_NAME }} to App ECR'
+      #     docker tag  ${{ env.GITHUB_IMAGE_REPO }}/${{ env.DUMMY_IMAGE_NAME }}:latest ${{ env.APP_ECR_REPO_URL }}:${{ env.DUMMY_IMAGE_NAME }}
+      #     docker push ${{ env.APP_ECR_REPO_URL }}:${{ env.DUMMY_IMAGE_NAME }}
 
-      - name: Check dummy-image in Lambda ECR exists
-        id: lambda-ecr-check
-        shell: bash
-        run: |
-          IMAGE_TAG=${{ env.DUMMY_IMAGE_NAME }}
-          REPOSITORY_NAME=${{ vars.APP_NAME }}-lambda-repo-${{ env.environment }}
+      # - name: Check dummy-image in Lambda ECR exists
+      #   id: lambda-ecr-check
+      #   shell: bash
+      #   run: |
+      #     IMAGE_TAG=${{ env.DUMMY_IMAGE_NAME }}
+      #     REPOSITORY_NAME=${{ vars.APP_NAME }}-lambda-repo-${{ env.environment }}
           
-          IMAGE_EXISTS=$(aws ecr describe-images --repository-name $REPOSITORY_NAME --query "imageDetails[?contains(imageTags, '$IMAGE_TAG')]" --output text)
+      #     IMAGE_EXISTS=$(aws ecr describe-images --repository-name $REPOSITORY_NAME --query "imageDetails[?contains(imageTags, '$IMAGE_TAG')]" --output text)
 
-          if [ -z "$IMAGE_EXISTS" ]; then
-            echo "Image with tag $IMAGE_TAG does not exist."
-            echo "exists=false" >> $GITHUB_OUTPUT
-          else
-            echo "Image with tag $IMAGE_TAG already exists."
-            echo "exists=true" >> $GITHUB_OUTPUT
-          fi
+      #     if [ -z "$IMAGE_EXISTS" ]; then
+      #       echo "Image with tag $IMAGE_TAG does not exist."
+      #       echo "exists=false" >> $GITHUB_OUTPUT
+      #     else
+      #       echo "Image with tag $IMAGE_TAG already exists."
+      #       echo "exists=true" >> $GITHUB_OUTPUT
+      #     fi
 
-      - name: Push dummy images to Lambda ECR
-        if: steps.lambda-ecr-check.outputs.exists == 'false'
-        shell: bash
-        run: |
-          echo 'Deploying ${{ env.env.DUMMY_IMAGE_NAME }} to Lambda ECR'
-          docker tag  ${{ env.GITHUB_IMAGE_REPO }}/${{ env.DUMMY_IMAGE_NAME }}:latest ${{ env.LAMBDA_ECR_REPO_URL }}:${{ env.DUMMY_IMAGE_NAME }}
-          docker push ${{ env.LAMBDA_ECR_REPO_URL }}:${{ env.DUMMY_IMAGE_NAME }}
+      # - name: Push dummy images to Lambda ECR
+      #   if: steps.lambda-ecr-check.outputs.exists == 'false'
+      #   shell: bash
+      #   run: |
+      #     echo 'Deploying ${{ env.env.DUMMY_IMAGE_NAME }} to Lambda ECR'
+      #     docker tag  ${{ env.GITHUB_IMAGE_REPO }}/${{ env.DUMMY_IMAGE_NAME }}:latest ${{ env.LAMBDA_ECR_REPO_URL }}:${{ env.DUMMY_IMAGE_NAME }}
+      #     docker push ${{ env.LAMBDA_ECR_REPO_URL }}:${{ env.DUMMY_IMAGE_NAME }}
 
-      - name: Terraform Plan (Main Stack)
-        id: plan-main
-        run: |
-          terraform plan -no-color -input=false -var-file=${{ env.environment }}.tfvars
-        continue-on-error: true
-        working-directory: ${{ env.WORKING_DIRECTORY }}
+      # - name: Terraform Plan (Main Stack)
+      #   id: plan-main
+      #   run: |
+      #     terraform plan -no-color -input=false -var-file=${{ env.environment }}.tfvars
+      #   continue-on-error: true
+      #   working-directory: ${{ env.WORKING_DIRECTORY }}
   
-      - name: Terraform Plan (Main) Status
-        if: steps.plan-main.outcome == 'failure'
-        run: exit 1
+      # - name: Terraform Plan (Main) Status
+      #   if: steps.plan-main.outcome == 'failure'
+      #   run: exit 1
 
-      - name: Terraform Apply (Main Stack)
-        run: |
-          terraform apply --auto-approve -input=false -var-file=${{ env.environment }}.tfvars
-        working-directory: ${{ env.WORKING_DIRECTORY }}        
+      # - name: Terraform Apply (Main Stack)
+      #   run: |
+      #     terraform apply --auto-approve -input=false -var-file=${{ env.environment }}.tfvars
+      #   working-directory: ${{ env.WORKING_DIRECTORY }}        
